import { AppSidebar } from "@/components/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pixel AI Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <div className="w-fit flex items-center gap-2 px-4 my-4">
          <SidebarTrigger className="ml-2" />
        </div>
        <main className="flex flex-1 flex-col gap-4 p-4 pt-0">
          {children}
          {/* <Toaster richColors /> */}
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}
